baseurl = "https://www.problemofpoints.com"
DefaultContentLanguage = "en"

title = "Problem of Points"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = false
pygmentCodeFences = false
#disqusShortname = "problemofpoints"
googleAnalytics = "UA-101215414-1"

relativeurls = true
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[Params]
  subtitle = "Capital allocation in an uncertain world"
#  logo = "img/avatar-icon.png"
  favicon = "img/favicons-black-letter-P.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = false
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
[[Params.bigimg]]
  src = "img/hexagon.jpg"
  desc = "Hexagon"

#[Author]
#  name = "Some Person"
#  email = "youremail@domain.com"
#  github = "username"
#  twitter = "username"

[[menu.main]]
    name = "Blog"
#    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3

