baseurl = "https://www.problemofpoints.com"
theme = "cocoa-eh-hugo-theme"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = ""
title = "Problem of Points"
disqusshortname = ""
pluralizelisttitles = false
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
googleAnalytics = "UA-101215414-1"

[permalinks]
  blog = "/blog/:year/:month/:day/:slug/"


[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 CST"
description = "Capital allocation in an uncertain world"
copyright = "Copyright © 2018 problemofpoints | Disclaimer"
# copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
logofile = "img/favicons-black-letter-P.ico"
faviconfile = "img/favicons-black-letter-P.ico"
highlightjs = true
# options for highlight.js (version, additional languages, and theme)
highlightjsVersion = "9.11.0"
highlightjsCDN = "https://cdn.bootcss.com"
highlightjsLang = ["r", "yaml"]
highlightjsTheme = "github"
progressively = true
share = false
latestpostcount = 10
usesmallsummarycard = true
posts_navigation = true
# githubRepo = "githubUsername/repositoryName/tree/master"
small_banner_logo = true
#large_banner_logo = true
noreadingtime = true
align_left = false
uselatex = true
#titlestyle = "capitalize"

#[params.colors]
#identifier = "#527fc1f"
#identifier_dark = "#1a3152"
#trivial = "#6a7a8b"
#foreground = "#181d2a"
#background = "#f9f9f9"
#background_dark = "#282a36"
#code = "#87a5d2"
#type = "#97d28b"
#special = "#ffcb8d"
#value = "#96c2d7"
#statement = "#ff8e91"
