[build]
command = """
  curl -LO https://quarto.org/download/latest/quarto-linux-amd64.deb && \
  dpkg -x quarto-linux-amd64.deb . && \
  rm quarto-linux-amd64.deb && \
  ./opt/quarto/bin/quarto render
"""
publish = "_site"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[dev]
command = "quarto preview --port 8888 --no-browser"
targetPort = 8888
port = 8889
autoLaunch = false
