---
title: "Q2 2017 Earnings Call Roundup 1"
author: ''
date: '2017-08-25'
categories: [insurance]
subtitle: ''
draft: false
---

Quotes from Q2 2017 earnings calls related to innovation, future strategy, or capital allocation.

# Travelers

> We are focused on our digital agenda on advancing the way we leverage data on exploring and piloting smart investments and things like AI and robotics on setting the standard in terms of the experience for our customers and distribution partners and as always on being as productive and efficient as possible. - Alan Schnitzer, CEO Travelers

# W.R. Berkley

> We are an industry that historically and today sell product to customers in the manner we sell them what we want and we give it to them the way we want to give it to them or distribute it the way we want to. It is our view that going forward over time you're going to see a bit of an evolution where customers are going to drive more and more what the product is and how it is distributed and the if you will buffer known as regulation that has kept much of this change from occurring today is also primed for a degree of change as regulators are becoming more in touch with the needs of society and looking to be responsive to that. - Robert Berkley, CEO W.R. Berkley

# Chubb

> We are investing substantial sums, talent and time in positioning this Company to be a leader in a digital age, because the economy globally is digitizing. This includes our organization structure, cycle times of change, expertise and skill sets of our people, data and analytics, robotics, the front-end customer experience to the customer back-end claims experience and the very definition of the products we sell. This is not just strategy, we are quietly executing. - Evan Greenberg, CEO Chubb

> But at the same time those same capabilities will be delivered through new clients at the intermediary, dot-com type intermediaries, where potential customers are buying other services and products and its natural that it at that time they consider insurance, you are licensing your business your small business, you are setting up the accounting and financing of your small business. It's a time that you will consider insurance as an example, there will be many like that. You taking out a loan for your business and technology enables those other forms of distribution. The customer will buy it from a desktop, the customer will buy it from a mobile device, they will buy it any time anywhere and they will service it anytime anywhere. This is not futuristic in the sense of measuring it in years from now. It's on our door step, this is the next two years or shorter, it will be iterative, it will only get better and better and better. There won't be one winner, there will be a number of them. - Evan Greenberg, CEO Chubb

# XL Group

> In product innovation, we introduced 12 new products and services in the quarter...We have long seen our drive for innovation as it being equally about our reputation and our ability to think about the future on behalf of our clients, as it is a real remixing opportunity, pivoting an increasing percent of our portfolio towards better performing and more relevant businesses.

# AXIS Capital

> Our risk funding flexibility is key as we match risks with the best source and form of capital. This will enable us to keep providing attractive risk to capital partners while enhancing our ROE and benefiting our own shareholders.

Sources:

-   [The Travelers' (TRV) CEO Alan Schnitzer on Q2 2017 Results - Earnings Call Transcript](https://seekingalpha.com/article/4089124-travelers-trv-ceo-alan-schnitzer-q2-2017-results-earnings-call-transcript)
-   [W.R. Berkley's (WRB) CEO Robert Berkley on Q2 2017 Results - Earnings Call Transcript](https://seekingalpha.com/article/4090509-w-r-berkleys-wrb-ceo-robert-berkley-q2-2017-results-earnings-call-transcript)
-   [Chubb's (CB) CEO Evan Greenberg on Q2 2017 Results - Earnings Call Transcript](https://seekingalpha.com/article/4090742-chubbs-cb-ceo-evan-greenberg-q2-2017-results-earnings-call-transcript)
-   [XL Group (XL) Q2 2017 Results - Earnings Call Transcript](https://seekingalpha.com/article/4091076-xl-group-xl-q2-2017-results-earnings-call-transcript)
-   [AXIS Capital's (AXS) CEO Albert Benchimol on Q2 2017 Results - Earnings Call Transcript](https://seekingalpha.com/article/4091335-axis-capitals-axs-ceo-albert-benchimol-q2-2017-results-earnings-call-transcript)
