---
title: 2018 (Re)Insurer Stock Price Performance
author: ''
date: '2019-02-17'
slug: 2018-re-insurer-stock-price-performance
categories: []
tags:
  - insurance
  - stocks
draft: true
---

```{r setup, warning=FALSE,message=FALSE,include=FALSE}

library(knitr)

knitr::opts_chunk$set(
	fig.align = "center",
	message = FALSE,
	warning = FALSE,
	echo = FALSE,
	collapse = TRUE,
  comment = "#>",
  out.width = "120%"
)

library(tidyverse)
library(tidyquant)
library(popformatting)
```

# Goal

In this post, we review the 2018 stock price returns for US property and casualty (re)insurers. 

```{r import-stock-prices, message=FALSE, warning=FALSE, cache=TRUE}

start_stock <- as_date("2018-01-01")
end_stock <- as_date("2018-12-31")

# get a list of all the Property-Casualty Insurers from the major US stock exchanges
stock_tickers <- list('AMEX','NASDAQ','NYSE') %>% map_df(tq_exchange) %>% 
  filter((industry == 'Property-Casualty Insurers' | symbol %in% c("ARGO", "ERIE", "AIZ")) & !is.na(market.cap)) %>%
  mutate(market_cap = if_else(stringr::str_sub(market.cap,start = -1)=="M",1e6,1e9) *
           as.numeric(stringr::str_sub(market.cap,start = 2, end = -2))) %>%
  dplyr::select(symbol, company, sector, industry, market_cap) %>%
  arrange(desc(market_cap))

# now get the historical stock prices for all of the tickers; calculate daily returns
stock_prices <- stock_tickers %>% 
  tq_get(get = "stock.prices", from = start_stock, to = end_stock) %>% 
  filter(!is.na(adjusted)) %>% 
  dplyr::group_by(symbol) %>%
  tq_mutate(select = adjusted, mutate_fun = periodReturn, period = "daily", type = "arithmetic", 
            col_rename = "daily_returns") %>% 
  mutate(cum_return = adjusted / dplyr::first(adjusted) - 1)

# get S&P 500 historical prices; use for comparison
sp500_price <- tibble(symbol = "SPY") %>% tq_get(get = "stock.prices", 
                                                 from = start_stock, to = end_stock) %>%
  tq_mutate(select = adjusted, mutate_fun = periodReturn, period = "daily", type = "arithmetic", 
            col_rename = "daily_returns") %>% 
  mutate(cum_return = adjusted / dplyr::first(adjusted) - 1)


sp500_price <- sp500_price %>% mutate(sp500 = adjusted, sp500_returns = daily_returns)
stock_prices <- stock_prices %>% 
  left_join(sp500_price %>% dplyr::select(date, sp500, sp500_returns), by = "date")
```

```{r cum-change}
annual_returns <- stock_prices %>% 
  summarise(market_cap = market_cap[1], 
            return = dplyr::last(cum_return), min_return = min(cum_return), max_return = max(cum_return),
            min_price = min(adjusted), max_price = max(adjusted), 
            avg_return = mean(daily_returns), sd_returns = sd(daily_returns),
            up_days = sum(daily_returns>0), down_days = sum(daily_returns<0)) %>% 
  arrange(desc(return))

annual_returns
```

```{r graph-stock-price}
stock_prices %>% 
  ungroup() %>% 
  filter(symbol %in% annual_returns$symbol[1:6]) %>%
  mutate(symbol = factor(symbol, levels = annual_returns$symbol[1:6])) %>%
  ggplot(aes(x = date, y = close, group = symbol)) +
  geom_candlestick(aes(open = open, high = high, low = low, close = close)) +
  labs(title = "2018 P&C Insurers Stock Price", 
       y = "Closing Price", x = "") + 
  facet_wrap(~ symbol, ncol = 2, scale = "free_y") + 
  popformatting::gg_pop_theme()
```

```{r highchart}
library(highcharter)

hc_data <- stock_prices %>% 
  filter(symbol %in% annual_returns$symbol[1:6]) %>%
  ungroup() %>% 
  mutate(cum_return = cum_return) %>% 
  select(date, symbol, cum_return) %>% 
  spread(key = symbol, value = cum_return) %>% 
  timetk::tk_xts()

hc <- highchart(type = "stock") %>% 
  hc_title(text = "Top P&C Stocks in 2018") %>% 
  hc_subtitle(text = "Insert comment here") %>% 
  hc_add_series(hc_data[,1], name = names(hc_data[,1])) %>% 
  hc_add_series(hc_data[,2], name = names(hc_data[,2])) %>%
  hc_add_series(hc_data[,3], name = names(hc_data[,3])) %>%
  hc_add_series(hc_data[,4], name = names(hc_data[,4])) %>%
  hc_add_series(hc_data[,5], name = names(hc_data[,5])) %>%
  hc_add_series(hc_data[,6], name = names(hc_data[,6])) %>%
  hc_tooltip(pointFormat = "<span style=\"color:{series.color}\">{series.name}</span>:<b>{point.y:.3f}</b><br/>",
             shared = TRUE) %>% 
  hc_legend(enabled = TRUE) %>% 
  hc_add_theme(hc_theme_smpl())

hc
```

