---
title: Impact of Harvey on Insurer Stock Prices - Part 2
author: ''
date: '2017-09-07'
slug: impact-of-harvey-on-insurer-stock-prices-part-2
categories: []
tags:
  - stocks
subtitle: ''
draft: true
---

```{r setup}

knitr::opts_chunk$set(
	# fig.align = "center",
	# fig.path = "figures/",
	message = FALSE,
	warning = FALSE,
	echo = FALSE 
)

library(tidyverse)
library(tidyquant)
library(CausalImpact)

```

```{r set-dates}

start_event <- as_date("2017-08-23")
end_event <- as_date("2017-09-02")
start_stock <- as_date("2017-01-01")
start_graph <- end_event - weeks(6)

```

```{r import-stock-prices, eval=FALSE, message=FALSE, warning=FALSE, cache=TRUE, include=FALSE}

# get a list of all the Property-Casualty Insurers from the major US stock exchanges
stock_tickers <- list('AMEX','NASDAQ','NYSE') %>% map_df(tq_exchange) %>% 
  filter((industry == 'Property-Casualty Insurers' | symbol %in% c("AGII", "ERIE", "AIZ")) & !is.na(market.cap)) %>%
  mutate(market_cap = if_else(stringr::str_sub(market.cap,start = -1)=="M",1e6,1e9) *
           as.numeric(stringr::str_sub(market.cap,start = 2, end = -2))) %>%
  dplyr::select(symbol, company, sector, industry, market_cap) %>%
  arrange(desc(market_cap))

# get shares outstanding from most recent 10Q balance sheet; per Google finance
stock_shares <- stock_tickers %>% tq_get(get = "financials") %>% group_by(symbol) %>% 
  filter(type == "BS") %>% mutate(shares = map_dbl(quarter, ~ .x$value[.x$group == 42][1] * 1e6)) %>%
  dplyr::select(symbol, shares)

# not able to get XL shares outstanding, so manually put it in as of Q2 2017
stock_tickers <- stock_tickers %>% left_join(stock_shares, by = "symbol") %>%
  mutate(shares = if_else(symbol == "XL", 257.94 * 1e6, shares)) %>% filter(!is.na(shares))

# now get the historical stock prices for all of the tickers; calculate daily returns
stock_prices <- stock_tickers %>% tq_get(get = "stock.prices", from = start_stock, to = end_event) %>% 
  filter(!is.na(adjusted)) %>% dplyr::group_by(symbol) %>%
  tq_mutate(select = adjusted, mutate_fun = periodReturn, period = "daily", type = "arithmetic", 
            col_rename = "daily_returns")

# get S&P 500 historical prices; use for comparison and CausalImpact calculation
sp500_price <- tibble(symbol = "SPY") %>% tq_get(get = "stock.prices", 
                                                 from = start_stock, to = end_event) %>%
  tq_mutate(select = adjusted, mutate_fun = periodReturn, period = "daily", type = "arithmetic", 
            col_rename = "daily_returns")

sp500_price <- sp500_price %>% mutate(sp500 = adjusted, sp500_returns = daily_returns)
stock_prices <- stock_prices %>% left_join(sp500_price %>% dplyr::select(date, sp500, sp500_returns), by = "date")

```


```{r causal-impact-1, eval=FALSE, include=FALSE}

run_causal_impact <- function(stock_data){
  
  model_data_mat <- stock_data %>% ungroup() %>% 
    mutate(var = if_else(daily_returns > 0.02, 1, 0)) %>%
    # dplyr::select(adjusted, sp500) %>%
    dplyr::select(daily_returns, sp500_returns, var) %>%
    as.matrix()
  
  impact_analysis <- CausalImpact(model_data_mat,
                                  pre.period = c(1, nrow(model_data_mat) - 7),
                                  post.period = c(nrow(model_data_mat)-7+1, nrow(model_data_mat)),
                                  model.args = list(niter = 1000, prior.level.sd = 0.1))
  
  impact_analysis
}

impact_model <- run_causal_impact(stock_prices %>% filter(symbol == "AXS"))

plot(impact_model)
summary(impact_model)
# plot(impact_analysis$model$bsts.model, y = "components")


```

```{r causal-impact-2, eval=FALSE, cache=TRUE, include=FALSE}

causal_models <- stock_prices %>% #filter(symbol %in% stock_tickers$symbol[1:20]) %>%
  group_by(symbol, company, sector, industry, market_cap) %>% nest() %>%
  mutate(model = map(data, ~run_causal_impact(.x))) %>% dplyr::select(-data)

causal_models <- causal_models %>% 
  mutate(model_summary = map(model, ~ as_tibble(.x$summary[2,]))) %>% 
  unnest(model_summary)

```

```{r output, eval=FALSE, include=FALSE}

causal_models %>% arrange(AbsEffect)


```

