---
title: Digitization of Insurance Companies
subtitle: Still a long way to go...
date: 2017-10-17
slug: digitization-of-insurance-companies
categories:
    - insurance
    - insurtech
draft: false
---

In an article for the August 2017 edition of A.M. Best's Review, Bill Pieroni, CEO of ACORD, discusses findings from their recent *Insurance Digital Maturity Study*. The results are not encouraging and highlight the work left to be done in insurance.

**Key findings:**

-   Only about 40% of the top 100 worldwide insurers have digitized their insurance value chain
-   More than 10% are not leveraging digital technologies within their current business processes
-   Insurers who embrace digitization perform better, achieving premium and earnings growth of double the industry average
-   More than two-thirds of change efforts failed to meet expectations

The article lists seven reasons insurers struggle with going digital, including risk aversion and focusing on the past. Many insurers will not change until they are forced to. We are not at that point yet, but by the time many companies act, it will be too late. We need to change incentives and how we measure success now in order to foster innovation and change.

According to the article, four common attributes of successful change efforts were identified:

-   Rationale and a focus on both issues and opportunities
-   Well-defined goals and objectives
-   Effective leadership
-   Planning - detailed plan, stayed on-task and on-time

> Digitization and the ability to successfully execute change will be a critical source of tactical and strategic advantage moving forward.

[Press release for the ACORD study](https://www.acord.org/media/pressreleases/Pages/ACORD-Releases-White-Paper-Examining-Digitization-in-Top-100-Global-Insurance-Carriers-.aspx)
